### ISSUE TITLE
Redis error on startup

### ISSUE THREAD

**Issue by aaronflorey** [29decibel/hackernews-feed#2]
2013-07-23T09:20:55.568131+00:00 heroku[web.1]: Starting process with command `node server.js`
2013-07-23T09:20:56.909652+00:00 app[web.1]: Listening on 49496
2013-07-23T09:20:57.467555+00:00 heroku[web.1]: State changed from starting to up
2013-07-23T09:21:06.405485+00:00 app[web.1]:
2013-07-23T09:21:06.406259+00:00 app[web.1]: /app/node_modules/redis/index.js:551
2013-07-23T09:21:06.414764+00:00 app[web.1]: Error: protocol 'null' not supported
2013-07-23T09:21:06.407085+00:00 app[web.1]:                   ^
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at Error (<anonymous>)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at new Request (/app/node_modules/readabilitySAX/node_modules/minreq/index.js:53:22)
2013-07-23T09:21:06.406738+00:00 app[web.1]:             throw err;
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at module.exports (/app/node_modules/readabilitySAX/node_modules/minreq/index.js:9:9)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at Object.module.exports [as get](/app/node_modules/readabilitySAX/node/getURL.js:28:12)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at /app/lib/link_readability.js:40:21
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at try_callback (/app/node_modules/redis/index.js:548:9)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at RedisClient.return_reply (/app/node_modules/redis/index.js:630:13)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at HiredisReplyParser.<anonymous> (/app/node_modules/redis/index.js:282:14)
2013-07-23T09:21:06.414764+00:00 app[web.1]:     at HiredisReplyParser.EventEmitter.emit (events.js:95:17)
2013-07-23T09:21:06.414953+00:00 app[web.1]:     at HiredisReplyParser.execute (/app/node_modules/redis/lib/parser/hiredis.js:43:18)
2013-07-23T09:21:06.673920+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path=/ host=aqueous-atoll-4856.herokuapp.com fwd="210.50.247.243" dyno=web.1 connect=0ms service=4581ms status=503 bytes=0
2013-07-23T09:21:08.349576+00:00 heroku[web.1]: Process exited with status 8
2013-07-23T09:21:08.368474+00:00 heroku[web.1]: State changed from up to crashed
2013-07-23T09:21:08.369950+00:00 heroku[web.1]: State changed from crashed to starting
2013-07-23T09:21:09.800211+00:00 heroku[web.1]: Starting process with command `node server.js`
2013-07-23T09:21:10.708009+00:00 app[web.1]: Listening on 41309
2013-07-23T09:21:11.084095+00:00 heroku[web.1]: State changed from starting to up

**Comment by 29decibel** [comment]
Hi @Mochaka did you add the redis service in heroku?

**Comment by 29decibel** [comment]
`heroku addons:add redistogo`
